modules/books/models/Books.php
<?php

namespace app\modules\books\models;

use app\modules\authors\models\Authors;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\db\Expression;
use yii\web\UploadedFile;

/**
 * This is the model class for table "books".
 */
class Books extends ActiveRecord
{

    /**
     *
     * @var string 
     */
    private $_doc;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'books';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'author_id'], 'required'],
            [['author_id'], 'integer'],
            [['name'], 'string', 'max' => 255],
            [['date'], 'safe'],
            [['preview'], 'file', 'extensions' => 'gif, jpg, png'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('books', 'ID'),
            'name' => Yii::t('books', 'Название'),
            'preview' => Yii::t('books', 'Обложка'),
            'date' => Yii::t('books', 'Дата издания'),
            'author_id' => Yii::t('books', 'Автор'),
            'create_date' => Yii::t('books', 'Дата создания'),
        ];
    }

    public function behaviors()
    {
        return [
            'Timestamp' => [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['create_date', 'update_date'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['update_date']
                ],
                'value' => new Expression('NOW()'),
            ]
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuthor()
    {
        return $this->hasOne(Authors::className(), ['id' => 'author_id']);
    }

    /**
     * 
     */
    public function afterFind()
    {
        $this->_doc = $this->preview;
    }

    /**
     * 
     * @return type
     */
    public function beforeValidate()
    {

        if (($file = UploadedFile::getInstance($this, 'preview')) && $file->error === 0) {
            $this->preview = self::saveUploaded($file, self::tableName());
        }

        return parent::beforeValidate();
    }

    /**
     * 
     * @param object $insert
     * @return type
     */
    public function beforeSave($insert)
    {
        if (empty($this->preview)) {
            $this->preview = $this->_doc;
        }

        return parent::beforeSave($insert);
    }

    /**
     * @param string $attribute
     * @param bool $abs
     * @param string $mode
     * @return string filename or false if there's no image
     */
    public function getFilePath($attribute, $abs = false, $mode = null)
    {
        if (!$this->$attribute) {
            return false;
        }

        $pathinfo = pathinfo($this->$attribute);
        return "/" . Yii::getAlias('media') . "/" . self::tableName() . "/" . $pathinfo['dirname'] . "/" . $pathinfo['filename'] . $mode . "." . $pathinfo['extension'];
    }

    /**
     * @param UploadedFile $file
     * @param string $path
     * @param bool $subdir
     * @return string new name
     */
    public static function saveUploaded($file, $path, $subdir = true)
    {
        $path = static::getStoragePath(true, $path);
        if ($subdir) {
            $subdir = static::generateSubdir($path);
        }
        else {
            $subdir = '';
            if (!is_dir($path)) {
                if (!is_dir(dirname($path))) {
                    mkdir(dirname($path));
                }
                mkdir($path);
            }
        }
        $newName = static::generateName($file->extension);
        $result = $subdir ? $subdir . '/' . $newName : $newName;
        $saved = $file->saveAs($path . '/' . $result);
        if (!$saved) {
            throw new \Exception('Could not save uploaded file: ' . $file->error . ' to path ' . $path . '/' . $result);
        }
        return $result;
    }

    public static function getStoragePath($abs = false, $name = null)
    {
        $path = \Yii::getAlias('media');

        if (!$name) {
            return $path;
        }
        else {
            return $path . '/' . trim($name, '/');
        }
    }

    public static function generateSubdir($path, $check = true)
    {
        if ($check && !is_dir($path)) {
            mkdir($path, 0777, true);
        }
        $subdir = time();
        //images with "ad" in path get blocked by adblocker
        if ($subdir == "ad") {
            $subdir = "/da";
        }
        if ($path && $check && !is_dir($path . '/' . $subdir)) {
            mkdir($path . '/' . $subdir);
        }
        return $subdir;
    }

    public static function generateName($ext, $suffix = null)
    {
        if (!$suffix) {
            return time() . '.' . $ext;
        }
        return time() . '-' . $suffix . '.' . $ext;
    }

}

modules/books/controllers/DefaultController.php
<?php

namespace app\modules\books\controllers;

use app\modules\books\models\Books;
use Yii;
use yii\web\Controller;

class DefaultController extends Controller
{

    /**
     * Displays a single Books model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {

        if (Yii::$app->request->isAjax) {
            return $this->renderAjax('view', [
                        'model' => $this->findModel($id),
            ]);
        }

        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Books model.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Books();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            // Закрываем форму и возвразаем на главную страницу
            print '<script type="text/javascript">opener.window.location.reload();window.close();</script>';
        }
        else {
            return $this->render('create', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Books model.
     * If update is successful, the browser will be redirected to the 'mainpage' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            print '<script type="text/javascript">opener.window.location.reload();window.close();</script>';
        }
        else {
            return $this->render('update', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Books model.
     * If deletion is successful, the browser will be redirected to the 'mainpage' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['/']);
    }

    /**
     * Finds the Books model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Books the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Books::findOne($id)) !== null) {
            return $model;
        }
        else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

modules/books/views/default/_form.php
<?php

use app\modules\authors\models\Authors;

use yii\helpers\Html;
use yii\jui\DatePicker;
use yii\widgets\ActiveForm;

use himiklab\colorbox\Colorbox;

echo Colorbox::widget([
    'targets' => [
        '.colorbox' => [
            'maxHeight' => 800
        ]
    ],
    'coreStyle' => 5
]);

/* @var $this yii\web\View */
/* @var $model app\modules\books\models\Books */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="books-form">
    <div class="widget">
        <div class="widget-content padding">
            <?php $form = ActiveForm::begin([
                    'enableClientValidation' => ($model->isNewRecord) ? true : false,
                    'options' => ['enctype' => 'multipart/form-data']
                ]); ?>

            <?= $form->field($model, 'name')->textInput(['maxlength' => 255]); ?>

            <?= $form->field($model, 'preview')->fileInput(); ?>

            <?php if($model->preview): ?>
            <div class="form-group">
                <p><?= Html::a(Html::img($model->getFilePath('preview'), ['width' => '100']), $model->getFilePath('preview'), ['class' => 'colorbox']); ?></p>
                <div class="help-block">
                    <p class="text-info">
                        <em>Загрузка нового отменяет старый</em>
                    </p>
                </div>
            </div>
            <?php endif; ?>
            
            <?= $form->field($model, 'date')->widget(DatePicker::className(), [
                'options' => ['class' => 'form-control'],
                'dateFormat' => 'php:d.m.Y'
            ]); ?>
            
            <?= $form->field($model, 'author_id')->dropDownList(Authors::getAuthors(), ['prompt' => \Yii::t('books', 'Выберите автора')]); ?>

            <div class="form-group">
                <?= Html::submitButton($model->isNewRecord ? Yii::t('books', 'Создать') : Yii::t('books', 'Сохранить'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

modules/books/views/default/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\modules\books\models\Books */

$this->title = Yii::t('books', 'Создание книги');
?>
<div class="books-create">
    <div class="page-heading">
        <h1><?= Html::encode($this->title) ?></h1>
    </div>
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/books/views/default/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\modules\users\models\Users */

$this->title = Yii::t('users', 'Изменение пользователя: ', [
        'modelClass' => 'Users',
    ]) . ' ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('users', 'Пользователи'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('users', 'Изменение');
?>
<div class="users-update">

    <div class="page-heading">

        <h1><i class="icon-user"></i> <?= Html::encode($this->title) ?></h1>
    </div>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/books/views/default/view.php
<div class="widget">
    <div class="widget-header" style="text-align: center;"><h2><?= $model->name; ?> (<?= $model->author->getAuthorFio(); ?>, <?= date('d.m.Y', strtotime($model->date)); ?>)</h2></div>
    <div class="widget-content padding">
        <?php if($model->preview): ?>
        <img style="border: 1px solid #000; float: left; margin-right: 20px;" src="<?= $model->getFilePath('preview'); ?>" width="200"/>
        <?php endif; ?>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
            when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap 
            into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum 
            passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
            when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap 
            into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum 
            passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
            when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap 
            into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum 
            passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
            when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap 
            into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum 
            passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
        <span style="clear:both"></span>
    </div>
</div>